-- 2026-10-09 : migration "founder_20_plus_unit_listings_and_pro_contact_auth" (appliquée sur Supabase)
-- 1. get_public_pro_contact : réservé aux membres connectés (auth.uid() non nul, execute retiré à anon/public).
-- 2. enforce_founder_50_listing_limit : au-delà de la limite de la formule, consomme 1 crédit
--    de pro_listing_credit_wallet (annonce achetée à l'unité) ; sans crédit, message invitant à en acheter une.
-- 3. pro_subscription_plans : pro_50.founder_eligible = false (seule la formule 20 est gratuite 12 mois).
-- Correction même jour (règle confirmée par Anthony) :
-- Offre Fondateurs = formules 20 ET 50 gratuites 12 mois (pro_50.founder_eligible remis à true).
-- Fondateur 20 qui dépasse : passer en 50 Fondateurs (fonction change-pro-subscription-plan, garde gratuité et -50 %)
--   ou acheter l'annonce supplémentaire à l'unité. Fondateur 50 qui dépasse : annonce à l'unité (pas de 100 Fondateurs).
-- Migrations : founder_50_restored_and_limit_message, founder_limit_message_by_plan.
-- Harmonisation des prix en ,99 (demande d'Anthony) — nouveaux prix Stripe, anciens archivés :
-- hightech_10 29,90→29,99 (price_1UOdrZ1DkwXb4U3JYYgqxalq) ; hightech_30 abonnement 29,90→29,99/mois (price_1UOdrb1DkwXb4U3JuIHOjNKO)
-- hightech_pack30 69,90→69,99 (price_1UOdrd1DkwXb4U3JAFxpzAJI) ; maison_10 39,90→39,99 (price_1UOdre1DkwXb4U3Jb2NUzFhV)
-- maison_pack30 89,90→89,99 (price_1UOdrg1DkwXb4U3JdEjIvkv5). commerce_offers + pro_subscription_plans mis à jour.
-- pro_urgent_30 1,49→1,99 HT (price_1UOdwC1DkwXb4U3J49RKiuVK), ancien prix archivé.
-- pro_urgent_30 finalement : 9,99 € HT pour 60 jours (duration_days=60, label 'Urgent — 60 jours', price_1UOdy71DkwXb4U3JVKXv4xg4) ; prix 1,49 et 1,99 archivés.
-- Urgent (pro 9,99 HT, particulier 9,99 TTC) : jusqu'à la fin de l'annonce (expires_at), sinon 60 jours ; webhook stripe-pricing-v2-webhook v9.
