from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
old='''      <div class="categories">\n        <a class="cat category-link" href="#resultats" data-category="vehicules"><div class="cat-icon">🚘</div><div><h3>Véhicules</h3><small>Auto, moto, utilitaires et pièces</small></div></a>\n        <a class="cat category-link" href="#resultats" data-category="immobilier"><div class="cat-icon">🏠</div><div><h3>Immobilier</h3><small>Vente et location longue durée</small></div></a>\n        <a class="cat vacances-cat" href="vacances.html"><div class="cat-icon">🏖️</div><div><h3>Vacances</h3><small>Locations saisonnières en direct</small></div></a>\n        <a class="cat category-link" href="#resultats" data-category="hightech"><div class="cat-icon">📱</div><div><h3>High-tech</h3><small>Téléphones, ordinateurs et accessoires</small></div></a>\n        <a class="cat category-link" href="#resultats" data-category="maison"><div class="cat-icon">🛋️</div><div><h3>Maison</h3><small>Mobilier, déco, jardin et équipement</small></div></a>\n        <a class="cat category-link" href="#resultats" data-category="mode"><div class="cat-icon">👗</div><div><h3>Mode</h3><small>Vêtements, chaussures et accessoires</small></div></a>\n        <a class="cat category-link" href="#resultats" data-category="vehicules" data-sub="motos"><div class="cat-icon">🏍️</div><div><h3>Moto</h3><small>Motos, scooters et deux-roues</small></div></a>\n        <a class="cat category-link" href="#resultats" data-category="emploi"><div class="cat-icon">💼</div><div><h3>Emploi</h3><small>Offres et opportunités professionnelles</small></div></a>\n      </div>'''
new='''      <div class="categories">\n        <a class="cat category-link" href="#resultats" data-category="vehicules" data-sub="voitures"><div class="cat-icon">🚗</div><div><h3>Voiture</h3><small>Voitures, utilitaires et pièces auto</small></div></a>\n        <a class="cat category-link" href="#resultats" data-category="vehicules" data-sub="motos"><div class="cat-icon">🏍️</div><div><h3>Moto</h3><small>Motos, scooters et deux-roues</small></div></a>\n        <a class="cat category-link" href="#resultats" data-category="immobilier"><div class="cat-icon">🏠</div><div><h3>Immobilier</h3><small>Vente et location longue durée</small></div></a>\n        <a class="cat vacances-cat" href="vacances.html"><div class="cat-icon">🏖️</div><div><h3>Vacances</h3><small>Locations saisonnières en direct</small></div></a>\n        <a class="cat category-link" href="#resultats" data-category="hightech"><div class="cat-icon">📱</div><div><h3>High-tech</h3><small>Téléphones, ordinateurs et accessoires</small></div></a>\n        <a class="cat category-link" href="#resultats" data-category="maison"><div class="cat-icon">🛋️</div><div><h3>Maison</h3><small>Mobilier, déco, jardin et équipement</small></div></a>\n        <a class="cat category-link" href="#resultats" data-category="mode"><div class="cat-icon">👗</div><div><h3>Mode</h3><small>Vêtements, chaussures et accessoires</small></div></a>\n        <a class="cat category-link" href="#resultats" data-category="emploi"><div class="cat-icon">💼</div><div><h3>Emploi</h3><small>Offres et opportunités professionnelles</small></div></a>\n      </div>'''
count=s.count(old)
if count<1:
    raise SystemExit('Visible old category block not found')
s=s.replace(old,new)
p.write_text(s,encoding='utf-8')
print(f'Replaced {count} category block(s)')
Path('.github/abracadeal_patch.py').unlink(missing_ok=True)
Path('.github/workflows/abracadeal-publish.yml').unlink(missing_ok=True)
