from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')

# CSS for LOA badges and richer garage card.
css_anchor='''.seller-contact .btn.ghost:hover{\n  background:#f6eef9 !important;\n}\n.photo-preview{\n'''
css_new='''.seller-contact .btn.ghost:hover{\n  background:#f6eef9 !important;\n}\n.badge-row{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}\n.info-badge{display:inline-flex;align-items:center;gap:6px;padding:7px 11px;border-radius:999px;border:1px solid #e1d5ea;background:#fff;color:#604e69;font-size:.76rem;font-weight:850;line-height:1}\n.info-badge.pro{background:#f3ebf9;color:#6f2f8b;border-color:#dbc8e8}\n.info-badge.loa{background:linear-gradient(135deg,#1976ff 0%,#4da2ff 100%);color:#fff;border-color:#4da2ff;box-shadow:0 10px 20px rgba(27,121,255,.22)}\n.info-badge.loa strong{color:#fff}\n.detail-finance-note{margin-top:10px;color:#544776;font-weight:800;font-size:.9rem}\n.seller-badges{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:14px}\n.seller-badge-loa{background:linear-gradient(135deg,#1976ff 0%,#4da2ff 100%);color:#fff;border-color:#4da2ff;box-shadow:0 10px 20px rgba(27,121,255,.20)}\n.seller-public-shell{display:grid;grid-template-columns:72px 1fr auto;gap:14px;align-items:center}\n.seller-logo{width:72px;height:72px;border-radius:18px;background:linear-gradient(135deg,#ffffff 0%,#f5edf9 100%);border:1px solid #e8daef;display:flex;align-items:center;justify-content:center;box-shadow:inset 0 1px 0 rgba(255,255,255,.85)}\n.seller-logo span{display:inline-flex;align-items:center;justify-content:center;width:52px;height:52px;border-radius:16px;background:linear-gradient(135deg,#251434 0%,#5d2386 100%);color:#fff;font-weight:900;letter-spacing:.03em;font-size:1rem;text-transform:uppercase}\n.seller-summary h3{margin:0;font-size:1.08rem;line-height:1.25}\n.seller-summary p{margin:4px 0 0;color:#7d6d87;font-size:.86rem}\n.seller-rating-rich{display:flex;align-items:center;flex-wrap:wrap;gap:8px;margin-top:8px}\n.seller-rating-rich strong{color:#2c1636;font-size:1rem}\n.seller-arrow{font-size:1.6rem;color:#8f77a1;font-weight:700}\n.seller-quick-stats{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}\n.seller-stat-chip{display:inline-flex;align-items:center;gap:6px;padding:8px 11px;border-radius:999px;background:#fff;border:1px solid #e8dcef;color:#5f4c68;font-size:.78rem;font-weight:800}\n.seller-profile-link{width:100%;margin-top:14px;border:none;background:#f2ebf7;color:#5b2780;border-radius:14px;padding:11px 13px;font-weight:850;cursor:pointer}\n.seller-profile-link:hover{background:#ece2f4}\n.seller-contact{grid-template-columns:1fr 1fr}\n@media(max-width:760px){.seller-public-shell{grid-template-columns:64px 1fr}.seller-arrow{display:none}.seller-logo{width:64px;height:64px;border-radius:16px}.seller-logo span{width:46px;height:46px;border-radius:14px;font-size:.9rem}.seller-contact{grid-template-columns:1fr}}\n.photo-preview{\n'''
if css_anchor not in s:
    raise SystemExit('CSS anchor not found')
s=s.replace(css_anchor,css_new,1)

# Helpers to display real LOA data when supplied by the seller.
helper_anchor="""function listingHasPhotoPack(a){return a?.seller_type==='professionnel'?listingPhotoLimit(a)>=30:listingPhotoLimit(a)>=12}\nfunction visiblePhotosFor(a){const photos=[...(a.listing_photos||[])].sort((x,y)=>(x.position||0)-(y.position||0));return photos.slice(0,listingPhotoLimit(a))}\n"""
helper_new="""function listingHasPhotoPack(a){return a?.seller_type==='professionnel'?listingPhotoLimit(a)>=30:listingPhotoLimit(a)>=12}\nfunction euroNoCents(v){const n=Number(v);if(!Number.isFinite(n)||n<=0)return '';return new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n)}\nfunction listingFinancingMonthly(a){const raw=a?.loa_monthly ?? a?.monthly_payment ?? a?.financing_monthly ?? a?.finance_monthly ?? a?.credit_monthly ?? a?.monthly_price ?? null;if(raw===null||raw===undefined||raw==='')return null;const n=Number(String(raw).replace(/\\s/g,'').replace(/[^\\d,.-]/g,'').replace(',', '.'));return Number.isFinite(n)&&n>0?n:null}\nfunction listingHasLoa(a){if(!a||a.category!=='vehicules')return false;if(a?.loa_available===true||listingFinancingMonthly(a))return true;const hay=[a?.title,a?.description].filter(Boolean).join(' ').toLowerCase();return /\\b(loa|leasing|lld|ll?d|financement)\\b/.test(hay)}\nfunction listingLoaLabel(a){const monthly=listingFinancingMonthly(a);return monthly?`LOA dès ${euroNoCents(monthly)}/mois`:'LOA possible'}\nfunction sellerInitials(name){const clean=String(name||'').replace(/[^\\p{L}\\p{N} ]/gu,' ').trim();if(!clean)return 'PRO';const parts=clean.split(/\\s+/).filter(Boolean).slice(0,2);return (parts.map(p=>p[0]).join('')||clean.slice(0,2)).toUpperCase()}\nfunction visiblePhotosFor(a){const photos=[...(a.listing_photos||[])].sort((x,y)=>(x.position||0)-(y.position||0));return photos.slice(0,listingPhotoLimit(a))}\n"""
if helper_anchor not in s:
    raise SystemExit('Helper anchor not found')
s=s.replace(helper_anchor,helper_new,1)

# Cards: visible PRO and LOA tags.
card_anchor='''        <h3 class="ad-title">${esc(a.title)}</h3>\n        <div class="ad-price">${money(a.price)}</div>\n        ${(a.category==='vehicules'&&(a.vehicle_year||a.mileage||a.fuel||a.transmission))?`<div class="ad-specs">\n'''
card_new='''        <h3 class="ad-title">${esc(a.title)}</h3>\n        <div class="ad-price">${money(a.price)}</div>\n        ${(a.seller_type==='professionnel'||listingHasLoa(a))?`<div class="badge-row">\n          ${a.seller_type==='professionnel'?`<span class="info-badge pro">PRO</span>`:''}\n          ${listingHasLoa(a)?`<span class="info-badge loa">${listingLoaLabel(a)}</span>`:''}\n        </div>`:''}\n        ${(a.category==='vehicules'&&(a.vehicle_year||a.mileage||a.fuel||a.transmission))?`<div class="ad-specs">\n'''
if card_anchor not in s:
    raise SystemExit('Card anchor not found')
s=s.replace(card_anchor,card_new,1)

# Detail header: highlight financing.
detail_anchor='''              <h1 class="detail-title-main">${esc(a.title)}</h1>\n              <div class="detail-price-main">${money(a.price)}</div>\n              <div class="detail-location">📍 ${esc(a.city)}${a.postal_code?` (${esc(a.postal_code)})`:''}</div>\n              <div class="detail-meta-line">${esc(categoryLabel)}${created?' · Publiée le '+esc(created):''}</div>\n'''
detail_new='''              <h1 class="detail-title-main">${esc(a.title)}</h1>\n              <div class="detail-price-main">${money(a.price)}</div>\n              <div class="detail-location">📍 ${esc(a.city)}${a.postal_code?` (${esc(a.postal_code)})`:''}</div>\n              ${(a.seller_type==='professionnel'||listingHasLoa(a))?`<div class="badge-row">\n                ${a.seller_type==='professionnel'?`<span class="info-badge pro">PRO</span>`:''}\n                ${listingHasLoa(a)?`<span class="info-badge loa">${listingLoaLabel(a)}</span>`:''}\n              </div>`:''}\n              ${listingHasLoa(a)?`<div class="detail-finance-note">Financement disponible ${listingFinancingMonthly(a)?`· à partir de <strong>${euroNoCents(listingFinancingMonthly(a))}/mois</strong>`:''}</div>`:''}\n              <div class="detail-meta-line">${esc(categoryLabel)}${created?' · Publiée le '+esc(created):''}</div>\n'''
if detail_anchor not in s:
    raise SystemExit('Detail anchor not found')
s=s.replace(detail_anchor,detail_new,1)

seller_anchor='''        <aside>\n          <div class="seller-card">\n            <span class="seller-badge">${a.seller_type==='professionnel'?'PRO':'PARTICULIER'}</span>\n            <div id="sellerPublic-${a.id}">\n              <h3>${sellerLabel}</h3>\n              <p>${esc(a.city)}</p>\n              <div class="seller-rating-line"><span class="stars">☆☆☆☆☆</span><span class="rating-muted">Chargement des avis…</span></div>\n            </div>\n            <button type="button" class="seller-profile-link" onclick="closeModal('detailModal');openSellerProfile('${a.owner_id}')">Voir le profil et les avis</button>\n\n            <div class="seller-contact">\n              ${!isOwner?`<button class="btn primary" type="button" onclick="startMessageForListing('${a.id}')">💬 Envoyer un message</button>`:''}\n              ${a.show_phone\n                ?`<div id="phoneContact-${a.id}"><button class="btn ghost" type="button" onclick="viewListingPhone('${a.id}')">📞 Voir le numéro</button><div class="contact-login-note">Le numéro est réservé aux membres connectés.</div></div>`\n                :`<div class="note">Le vendeur a choisi de ne pas afficher son numéro.</div>`}\n            </div>\n'''
seller_new='''        <aside>\n          <div class="seller-card">\n            <div class="seller-badges">\n              <span class="seller-badge">${a.seller_type==='professionnel'?'PRO':'PARTICULIER'}</span>\n              ${listingHasLoa(a)?`<span class="seller-badge seller-badge-loa">${listingLoaLabel(a)}</span>`:''}\n            </div>\n            <div id="sellerPublic-${a.id}">\n              <div class="seller-public-shell">\n                <div class="seller-logo"><span>${a.seller_type==='professionnel'?'PRO':'AB'}</span></div>\n                <div class="seller-summary">\n                  <h3>${sellerLabel}</h3>\n                  <p>${esc(a.city)}</p>\n                  <div class="seller-rating-rich"><span class="stars">☆☆☆☆☆</span><span class="rating-muted">Chargement des avis…</span></div>\n                </div>\n                <div class="seller-arrow">›</div>\n              </div>\n            </div>\n            <button type="button" class="seller-profile-link" onclick="closeModal('detailModal');openSellerProfile('${a.owner_id}')">${a.seller_type==='professionnel'?'Voir le garage et les avis':'Voir le profil et les avis'}</button>\n\n            <div class="seller-contact">\n              ${a.show_phone\n                ?`<div id="phoneContact-${a.id}"><button class="btn ghost" type="button" onclick="viewListingPhone('${a.id}')">📞 Voir le numéro</button><div class="contact-login-note">Le numéro est réservé aux membres connectés.</div></div>`\n                :`<div class="note">Le vendeur a choisi de ne pas afficher son numéro.</div>`}\n              ${!isOwner?`<button class="btn primary" type="button" onclick="startMessageForListing('${a.id}')">💬 Message</button>`:''}\n            </div>\n'''
if seller_anchor not in s:
    raise SystemExit('Seller card anchor not found')
s=s.replace(seller_anchor,seller_new,1)

# Rich garage profile data in the seller card.
start=s.find('async function hydrateSellerCard(sellerId,listingId){')
end=s.find('\n}\n\nlet reviewDraftRating=0;',start)
if start<0 or end<0:
    raise SystemExit('hydrateSellerCard block not found')
hydrate='''async function hydrateSellerCard(sellerId,listingId){\n  const host=document.getElementById(`sellerPublic-${listingId}`);\n  const ad=allAds.find(x=>x.id===listingId)||detailAdsCache.get(listingId);\n  if(!host) return;\n  const [{data:profile},{data:reviews},{data:sellerListings}]=await Promise.all([\n    sb.from('public_profiles').select('id,display_name,account_type,city,joined_at').eq('id',sellerId).maybeSingle(),\n    sb.from('reviews').select('rating').eq('seller_id',sellerId).eq('status','active'),\n    sb.from('listings').select('id').eq('owner_id',sellerId).eq('status','active').limit(200)\n  ]);\n  const list=reviews||[];\n  const avg=list.length?list.reduce((sum,r)=>sum+Number(r.rating),0)/list.length:0;\n  const displayName=profile?.display_name || (profile?.account_type==='professionnel'?'Garage professionnel':'Vendeur particulier');\n  const city=profile?.city||ad?.city||'';\n  const initials=sellerInitials(displayName);\n  const listingsCount=(sellerListings||[]).length;\n  const since=profile?.joined_at?new Intl.DateTimeFormat('fr-FR',{month:'short',year:'numeric'}).format(new Date(profile.joined_at)):'';\n  const isPro=(profile?.account_type==='professionnel')||(ad?.seller_type==='professionnel');\n  host.innerHTML=`\n    <div class="seller-public-shell">\n      <div class="seller-logo"><span>${esc(initials)}</span></div>\n      <div class="seller-summary">\n        <h3>${esc(displayName)}</h3>\n        <p>${isPro?'Garage / vendeur professionnel':'Vendeur particulier'}${city?` · ${esc(city)}`:''}</p>\n        <div class="seller-rating-rich">\n          <span class="stars">${starsText(avg)}</span>\n          <strong>${list.length?avg.toFixed(1).replace('.',','):'—'}</strong>\n          <span class="rating-muted">${list.length?`${list.length} avis`:'Aucun avis pour le moment'}</span>\n        </div>\n      </div>\n      <div class="seller-arrow">›</div>\n    </div>\n    <div class="seller-quick-stats">\n      ${isPro?`<span class="seller-stat-chip">🏢 ${listingsCount} annonce${listingsCount>1?'s':''}</span>`:''}\n      ${city?`<span class="seller-stat-chip">📍 ${esc(city)}</span>`:''}\n      ${since?`<span class="seller-stat-chip">📅 ${isPro?'Actif':'Membre'} depuis ${esc(since)}</span>`:''}\n    </div>`;\n}\n'''
s=s[:start]+hydrate+s[end+3:]

p.write_text(s,encoding='utf-8')
Path('.github/loa_garage_patch.py').unlink(missing_ok=True)
Path('.github/workflows/loa-garage-publish.yml').unlink(missing_ok=True)
