import {requireConsent,checkOptionListing,checkoutLegalText,WITHDRAWAL_TEXT} from './payment-guard.ts';
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;const SERVICE_ROLE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const admin=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false}});const stripeKey=Deno.env.get("STRIPE_SECRET_KEY")||Deno.env.get("STRIPE_RESTRICTED_KEY")||"";const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});async function stripeGet(path:string){const r=await fetch("https://api.stripe.com/v1/"+path,{headers:{Authorization:"Bearer "+stripeKey}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error("Stripe: "+(d?.error?.message||"Erreur Stripe"));return d}
const PHOTO_CATEGORY_RULES:Record<string,string[]>={photo_auto_moto_15:['vehicules'],photo_immo_15:['immobilier'],photo_lifestyle_10:['hightech','maison','mode'],photo_services_emploi_10:['services','emploi']};
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);try{const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)return json({error:"Connexion requise"},401);const {data:authData,error:authError}=await admin.auth.getUser(token);const user=authData?.user;if(authError||!user)return json({error:"Session invalide"},401);const body=await req.json().catch(()=>({}));const code=String(body?.offer_code||"").trim();const listingId=String(body?.listing_id||"").trim()||null;const {data:offer,error:offerError}=await admin.from("commerce_offers").select("*").eq("code",code).eq("active",true).maybeSingle();if(offerError||!offer||offer.recurring===true||(!offer.stripe_price_id&&offer.offer_type!=="modification"))return json({error:"Offre indisponible"},400);const {data:profile}=await admin.from("profiles").select("account_type").eq("id",user.id).maybeSingle();if(profile?.account_type!==offer.audience)return json({error:"Cette offre ne correspond pas à votre compte"},403);if(offer.audience==="professionnel"){const {data:v}=await admin.from("pro_verifications").select("verified_at").eq("user_id",user.id).maybeSingle();if(!v?.verified_at)return json({error:"Compte professionnel non vérifié"},403)}
 const isOption=["featured","urgent","photo_option","boost_pack","modification"].includes(String(offer.offer_type));if(isOption)requireConsent(body);let listing:any=null;const targetsListing=["featured","urgent","photo_option","boost_pack","modification"].includes(String(offer.offer_type))||offer.code==='private_vacances_30';if(targetsListing){if(!listingId)return json({error:"Annonce manquante"},400);const {data:l}=await admin.from("listings").select("id,owner_id,status,category,seller_type").eq("id",listingId).maybeSingle();listing=l;if(!listing||listing.owner_id!==user.id||["archived","rejected"].includes(String(listing.status)))return json({error:"Annonce non éligible"},403);if(String(listing.seller_type)!==String(offer.audience))return json({error:"Cette option ne correspond pas au type de l’annonce"},403);const allowed=PHOTO_CATEGORY_RULES[code];if(allowed&&!allowed.includes(String(listing.category)))return json({error:"Cette option photo ne correspond pas à la catégorie de l’annonce"},400);if(code==='private_vacances_30'&&String(listing.category)!=='vacances')return json({error:"Cette offre est réservée aux logements Vacances"},400)}
 if(isOption)await checkOptionListing(admin,SUPABASE_URL,listingId!);
 let revisionId:string|null=null;
 if(offer.offer_type==='modification'){
  const {data:revision}=await admin.from('listings').select('id,owner_id,revision_of,status').eq('id',String(body.revision_id||'')).maybeSingle();
  if(!revision||revision.owner_id!==user.id||revision.revision_of!==listingId||revision.status!=='pending')return json({error:'Version proposée manquante'},400);
  await checkOptionListing(admin,SUPABASE_URL,revision.id);const eligible=await admin.rpc('assert_listing_revision_checkout',{p_candidate_id:revision.id,p_owner_id:user.id});if(eligible.error)throw eligible.error;revisionId=revision.id;
 }
 if(revisionId){
 const {data:existing}=await admin.from('commerce_orders').select('id,status,stripe_checkout_session_id').eq('revision_id',revisionId).in('status',['pending','paid']).maybeSingle();
 if(existing?.status==='paid')return json({error:'Cette modification est déjà payée.'},409);
 if(existing){
  if(!existing.stripe_checkout_session_id)return json({error:'Un paiement est en cours de préparation. Réessayez dans quelques instants.'},409);
  const checkout=await stripeGet('checkout/sessions/'+encodeURIComponent(existing.stripe_checkout_session_id));
  if(checkout.status==='open'&&checkout.url)return json({ok:true,order_id:existing.id,checkout_url:checkout.url});
  if(checkout.status==='complete')return json({error:'Votre paiement est en cours de confirmation.'},409);
  await admin.from('commerce_orders').update({status:'cancelled'}).eq('id',existing.id).eq('status','pending');
 }
 }
 if(!stripeKey)return json({error:"Paiement Stripe indisponible"},503);if(offer.stripe_price_id){const price=await stripeGet("prices/"+encodeURIComponent(String(offer.stripe_price_id)));if(price?.active!==true||price?.livemode!==false||String(price?.currency)!==String(offer.currency)||price?.type!=="one_time"||Number(price?.unit_amount)!==Number(offer.amount_cents))return json({error:"Tarif Stripe incohérent avec le catalogue Abracadeal",payment_setup_pending:true},503);}const {data:order,error:orderError}=await admin.from("commerce_orders").insert({user_id:user.id,offer_code:offer.code,amount_cents:offer.amount_cents,currency:offer.currency,quantity:offer.quantity,status:"pending",listing_id:listingId,revision_id:revisionId,...(isOption?{withdrawal_accepted_at:new Date().toISOString(),withdrawal_text:WITHDRAWAL_TEXT}:{})}).select("*").single();if(orderError||!order)throw orderError||new Error("Commande impossible");const p=new URLSearchParams();p.set("mode","payment");p.set("client_reference_id",order.id);if(offer.stripe_price_id)p.set("line_items[0][price]",String(offer.stripe_price_id));else{
 p.set('line_items[0][price_data][currency]',offer.currency);p.set('line_items[0][price_data][unit_amount]',String(offer.amount_cents));p.set('line_items[0][price_data][product_data][name]',offer.label);
 }if(isOption)checkoutLegalText(p);p.set("line_items[0][quantity]","1");p.set("metadata[abraca_commerce_order]",order.id);let successUrl:string,cancelUrl:string;if(offer.code==='private_vacances_30'&&listingId){successUrl=`https://abracadeal.fr/photos-vacances.html?listing=${encodeURIComponent(listingId)}&commerce=success`;cancelUrl=`https://abracadeal.fr/photos-vacances.html?listing=${encodeURIComponent(listingId)}&commerce=cancel`}else{const returnPage=offer.audience==='professionnel'?"https://abracadeal.fr/pro-fondateur.html":"https://abracadeal.fr/options-annonce.html";successUrl=returnPage+"?commerce=success";cancelUrl=returnPage+"?commerce=cancel"}p.set("success_url",successUrl);p.set("cancel_url",cancelUrl);if(user.email)p.set("customer_email",user.email);const r=await fetch("https://api.stripe.com/v1/checkout/sessions",{method:"POST",headers:{Authorization:"Bearer "+stripeKey,"Content-Type":"application/x-www-form-urlencoded","Idempotency-Key":"commerce-"+order.id},body:p});const session=await r.json().catch(()=>({}));if(!r.ok||!session?.url){await admin.from('commerce_orders').update({status:'failed'}).eq('id',order.id).eq('status','pending');throw new Error("Stripe: "+(session?.error?.message||"création du paiement impossible"));}await admin.from("commerce_orders").update({stripe_checkout_session_id:session.id,updated_at:new Date().toISOString()}).eq("id",order.id);return json({ok:true,order_id:order.id,checkout_url:session.url})}catch(error){console.error(error);return json({error:error instanceof Error?error.message:"Erreur de paiement"},500)}});
